### ISSUE TITLE
Unable to launch Sugarbox.exe

### ISSUE THREAD

**Issue by 3ryX1988** [Tom1975/SugarboxV2#20]
Unable to launch Sugarbox.exe due to missing OpenAL32.dll.
Same error on 32 bit version & 64 bits version.

![image](https://user-images.githubusercontent.com/12666038/133928528-68eb028d-2306-4287-bbfe-7d266291fcc8.png)

Core i7 16 Go RAM Windows 10 with all updates

Greetings

**Comment by Tom1975** [comment]
Hello,

You can try install OpenAL, with the proper installer, which can be found here : 

https://openal.org/downloads/

SDK is not needed, just use the installer. It should fix your problem.

**Comment by Tom1975** [comment]
No news, I assume this installer did the job.
