### ISSUE TITLE
Configuration menu option does nothing

### ISSUE THREAD

**Issue by rmtew** [Tom1975/SugarboxV2#42]
Platform: Windows
Releases tried: 2.0.2 (win64) and 2.0.1 (win32)

The configuration menu is there, it does not matter what version of the CPC I have selected, but it clicking on elicits no action or response or display.

**Comment by Tom1975** [comment]
That's correct : I didn't make the port of old config dialog to new Sugarbox, so it's still an empty menu.
It's planned to be added.
