### ISSUE TITLE
Azerty Keyboard in all versions

### ISSUE THREAD

**Issue by Britlion** [Tom1975/SugarboxV2#44]
For some reason all the emulated computers  -  of any nationality - seem to have AZERTY keyboard layout for me. Can't seem to find anywhere to configure this.

**Comment by Tom1975** [comment]
Hello, I reproduced the problem : It seems that scan code I use depends on Keyboard.
If you install and select French Keyboard, you will be able to use your UK keyboard correctly.
I'll investigate this more deeply and fix it in the next release.

**Comment by Tom1975** [comment]
Will be soon released in 2.0.3 version
